### ISSUE TITLE
Makefile for scientific text production

### ISSUE THREAD

**Issue by lf-araujo** [robert-winkler/scientific-articles-markdown#19]
Dear Robert, 

Just recently I came accross your paper. Turns out I have been working in a makefile that handles the production of complex scientific documents using pandoc, similar to what you pushed in this repository. However, in my case it is also mostly OS agnostic, and handles installation of both a base latex distribution and handling packages dependencies. So, it is a more complete tool at this moment. Perhaps you want to take a look.

At some point I may insert a way of handling R scripts as well...

My repo is at: https://github.com/lf-araujo/mighty_make but look at the testing branch, as is where the installation and dependency handling routines were added. 

Best,

lf

**Comment by robert-winkler** [comment]
Dear If,

Is there a way how we could join effort? I am a 'professional writer' 
(scientist, 
https://scholar.google.com/citations?user=fyMS1UQAAAAJ&hl=de), so I am 
very happy about any initiative that makes formatting less painful.

I put Albert Krewinkel in the CC, because he is much more competent in 
all technological issues.

Best regards,


Robert

**Comment by lf-araujo** [comment]
Yes, absolutely. That is the reason I wrote you. I have adapted a bit more than a couple "templates" where I apply the same approach to write a letter, a cv, a scientific report and an entire scientific journal (this one I didn't have time to push into my repository) using the same underlying makefile.

There are limitations to the use of one Makefile, it is hard to make it fully compatible with windows and pandoc does not support complex tables at the moment.  I need help testing. So if you have a student in your lab that uses windows and wants to test it out in a Windows machine (and report bugs) that would help immensely.

**Comment by tarleb** [comment]
Hello Luis,

Joining forces would be great, I've send you an invitation to join the pandoc-scholar organization. I believe we should ensure backwards compatibility, but all improvement are very welcome.

I noted that mighty_make doesn't have a license yet, so technically we are not allowed to re-use it. Pandoc-scholar is <del>MIT</del> <ins>GPLv2+</ins> licensed, please indicate if this is OK for you.

The upcoming pandoc 2.0 will contain a couple of changes that will render large parts of the current pandoc-scholar script obsolete; e.g., JAGS is now supported out-of-the-box, plus we integrated lua filters into pandoc, so we'll no longer need to ship panlunatic, dhjson, etc.

Thanks,

Albert

**Comment by lf-araujo** [comment]
Hi Albert, 

Thanks for the invitation.

will read your documentation more carefully and try to incorporate your scripts into the makefile so to follow the standard you proposed. This will take some time as I am just finishing my PhD, but will let you know. GPL2 is fine with me, will update that there.


Best,
lf

**Comment by robert-winkler** [comment]
Dear If,

you will never have more time in your life than in the PhD ;-).

Please tell me, if I can contribute anything.

Best regards,


Robert
